### ISSUE TITLE
[scarthgap]{jazzy} Compilation issues of Scarthgap + meta-ros2-jazzy and possible solutions

### ISSUE THREAD

**Issue by Philip-abl** [ros/meta-ros#1515]
Hi @robwoolley and community,

Appreciate your great contributions as always!
I would like to ask you a question about the compile issue of Scarthgap + meta-ros2-jazzy. I look at the [Release table](https://github.com/ros/meta-ros/blob/master/README.md#supported-combinations) I can see such a combination. But I met some  errors when I start to compile it.  Some code branches don't exist anymore.

Is this combination ready to go? or we need to make some adapt changes to get it through? 

```bitbake
ERROR: Nothing PROVIDES 'ROS_UNRESOLVED_DEP-liblz4-dev' (but meta-ros/meta-ros2-jazzy/generated-recipes/rosbag2/liblz4-vendor_0.26.1-2.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'rosbag2-storage-mcap' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosbag2-storage-mcap', 'mcap-vendor', 'liblz4-vendor', 'ROS_UNRESOLVED_DEP-liblz4-dev']
NOTE: Runtime target 'rosbag2-storage-default-plugins' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosbag2-storage-default-plugins', 'rosbag2-storage-mcap', 'mcap-vendor', 'liblz4-vendor', 'ROS_UNRESOLVED_DEP-liblz4-dev']
NOTE: Runtime target 'rosbag2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['rosbag2', 'rosbag2-storage-default-plugins', 'rosbag2-storage-mcap', 'mcap-vendor', 'liblz4-vendor', 'ROS_UNRESOLVED_DEP-liblz4-dev']
NOTE: Runtime target 'ros-base' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-base', 'rosbag2', 'rosbag2-storage-default-plugins', 'rosbag2-storage-mcap', 'mcap-vendor', 'liblz4-vendor', 'ROS_UNRESOLVED_DEP-liblz4-dev']
ERROR: Required build target 'ros-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['ros-image', 'ros-base', 'rosbag2', 'rosbag2-storage-default-plugins', 'rosbag2-storage-mcap', 'mcap-vendor', 'liblz4-vendor', 'ROS_UNRESOLVED_DEP-liblz4-dev']
......
ERROR: shared-queues-vendor-0.26.1-2-r0 do_fetch: Fetcher failure: Unable to find revision dc17fed08353f30a7e20676df7c8fc5e842ed011 in branch release/jazzy/shared_queues_vendor even from upstream
ERROR: shared-queues-vendor-0.26.1-2-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/ros2-gbp/rosbag2-release;name=release;branch=release/jazzy/shared_queues_vendor;protocol=https')
......
ERROR: orocos-kdl-vendor-0.5.0-3-r0 do_fetch: Fetcher failure: Unable to find revision f1bbaed1b5190dbfefd08ca445e53d20d1a0066e in branch release/jazzy/orocos_kdl_vendor even from upstream
ERROR: orocos-kdl-vendor-0.5.0-3-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/ros2-gbp/orocos_kdl_vendor-release;name=release;branch=release/jazzy/orocos_kdl_vendor;protocol=https')
......
ERROR: mcap-vendor-0.26.1-2-r0 do_fetch: Fetcher failure: Unable to find revision af39b2f386c10c86cd74f4f78c908e46a0b0ae66 in branch release/jazzy/mcap_vendor even from upstream
ERROR: mcap-vendor-0.26.1-2-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/ros2-gbp/rosbag2-release;name=release;branch=release/jazzy/mcap_vendor;protocol=https')
......
ERROR: kdl-parser-2.11.0-3-r0 do_configure: ExecutionError(' /<out_path>/kdl-parser/2.11.0-3/temp/run.do_configure.3019563', 1, None, None)
ERROR: Logfile of failure stored in:  /<out_path>/kdl-parser/2.11.0-3/temp/log.do_configure.3019563
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are [' /<project_path>/poky/meta/recipes-core/glibc/glibc_2.39.bb:do_populate_sysroot', ' /<project_path>/poky/meta/recipes-devtools/cmake/cmake-native_3.28.3.bb:do_populate_sysroot', ' /<project_path>/poky/meta/recipes-devtools/gcc/gcc-cross_13.3.bb:do_populate_sysroot', ' /<project_path>/poky/meta/recipes-devtools/gcc/gcc-runtime_13.3.bb:do_populate_sysroot', ' /<project_path>/poky/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', ' /<project_path>/meta-ros/meta-ros2-jazzy/generated-recipes/orocos-kdl-vendor/orocos-kdl-vendor_0.5.0-3.bb:do_populate_sysroot', ' /<project_path>/meta-ros/meta-ros2-jazzy/generated-recipes/rcutils/rcutils_6.7.0-2.bb:do_populate_sysroot', ' /<project_path>/meta-ros/meta-ros2-jazzy/generated-recipes/urdf/urdf_2.10.0-3.bb:do_populate_sysroot', ' /<project_path>/meta-ros/meta-ros2-jazzy/generated-recipes/urdfdom-headers/urdfdom-headers_1.1.1-3.bb:do_populate_sysroot', 'virtual:native: /<project_path>/poky/meta/recipes-devtools/ninja/ninja_1.11.1.bb:do_populate_sysroot', 'virtual:native: /<project_path>/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native: /<project_path>/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native: /<project_path>/poky/meta/recipes-devtools/python/python3_3.12.9.bb:do_populate_sysroot', 'virtual:native:  /<project_path>/meta-ros/meta-ros2-jazzy/generated-recipes/ament-cmake-ros/ament-cmake-ros_0.12.0-3.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['openssl', 'expat', 'gettext-minimal-native', 'glibc', 'libxcrypt', 'ncurses', 'util-linux-libuuid', 'zlib', 'binutils-cross-aarch64', 'cmake-native', 'gcc-cross-aarch64', 'gcc-runtime', 'libgcc', 'libedit', 'libtool-native', 'm4-native', 'opkg-utils', 'python3', 'quilt-native', 'bzip2', 'libnsl2', 'libtirpc', 'texinfo-dummy-native', 'xz', 'linux-libc-headers', 'boost', 'gdbm', 'icu', 'libffi', 'sqlite3', 'libeigen', 'libtinyxml2', 'console-bridge', 'ament-index-cpp', 'class-loader', 'console-bridge-vendor', 'eigen3-cmake-module', 'orocos-kdl-vendor', 'pluginlib', 'rcpputils', 'rcutils', 'tinyxml2-vendor', 'urdf-parser-plugin', 'urdf', 'urdfdom-headers', 'urdfdom', 'openssl-native', 'expat-native', 'ncurses-native', 'util-linux-libuuid-native', 'zlib-native', 'flex-native', 'gnu-config-native', 'libedit-native', 'make-native', 'ninja-native', 'patch-native', 'perl-native', 'pseudo-native', 'python3-atomicwrites-native', 'python3-attrs-native', 'python3-build-native', 'python3-calver-native', 'python3-editables-native', 'python3-flit-core-native', 'python3-hatch-fancy-pypi-readme-native', 'python3-hatch-vcs-native', 'python3-hatchling-native', 'python3-importlib-metadata-native', 'python3-iniconfig-native', 'python3-installer-native', 'python3-more-itertools-native', 'python3-packaging-native', 'python3-pathlib2-native', 'python3-pathspec-native', 'python3-pip-native', 'python3-pluggy-native', 'python3-py-native', 'python3-pyparsing-native', 'python3-pyproject-hooks-native', 'python3-pytest-native', 'python3-setuptools-scm-native', 'python3-setuptools-native', 'python3-six-native', 'python3-toml-native', 'python3-tomli-native', 'python3-trove-classifiers-native', 'python3-typing-extensions-native', 'python3-wcwidth-native', 'python3-wheel-native', 'python3-zipp-native', 'python3-native', 'bzip2-native', 'libnsl2-native', 'libtirpc-native', 'unzip-native', 'xz-native', 'zstd-native', 'attr-native', 'gdbm-native', 'gmp-native', 'libffi-native', 'libmpc-native', 'mpfr-native', 're2c-native', 'sqlite3-native', 'googletest-native', 'python3-catkin-pkg-native', 'ament-cmake-ros-native', 'domain-coordinator-native', 'ament-cmake-core-native', 'ament-cmake-export-definitions-native', 'ament-cmake-export-dependencies-native', 'ament-cmake-export-include-directories-native', 'ament-cmake-export-interfaces-native', 'ament-cmake-export-libraries-native', 'ament-cmake-export-link-flags-native', 'ament-cmake-export-targets-native', 'ament-cmake-gen-version-h-native', 'ament-cmake-gmock-native', 'ament-cmake-gtest-native', 'ament-cmake-include-directories-native', 'ament-cmake-libraries-native', 'ament-cmake-pytest-native', 'ament-cmake-python-native', 'ament-cmake-target-dependencies-native', 'ament-cmake-test-native', 'ament-cmake-version-native', 'ament-cmake-native', 'ament-package-native', 'gmock-vendor-native', 'gtest-vendor-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| -- The C compiler identification is GNU 13.3.0
| -- The CXX compiler identification is GNU 13.3.0
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Check for working C compiler: /<out_path>/kdl-parser/2.11.0-3/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc - skipped
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Detecting CXX compiler ABI info
| -- Detecting CXX compiler ABI info - done
| -- Check for working CXX compiler:/<out_path>/kdl-parser/2.11.0-3/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ - skipped
| -- Detecting CXX compile features
| -- Detecting CXX compile features - done
| -- Found ament_cmake_ros: 0.12.0 (/<out_path>/kdl-parser/2.11.0-3/recipe-sysroot-native/opt/ros/jazzy/share/ament_cmake_ros/cmake)
| -- Found Python3: /<out_path>/kdl-parser/2.11.0-3/recipe-sysroot-native/usr/bin/python3-native/python3 (found version "3.12.9") found components: Interpreter
| CMake Error at CMakeLists.txt:6 (find_package):
|   By not providing "Findorocos_kdl_vendor.cmake" in CMAKE_MODULE_PATH this
|   project has asked CMake to find a package configuration file provided by
|   "orocos_kdl_vendor", but CMake did not find one.
| 
|   Could not find a package configuration file provided by "orocos_kdl_vendor"
|   with any of the following names:
| 
|     orocos_kdl_vendorConfig.cmake
|     orocos_kdl_vendor-config.cmake
| 
|   Add the installation prefix of "orocos_kdl_vendor" to CMAKE_PREFIX_PATH or
|   set "orocos_kdl_vendor_DIR" to a directory containing one of the above
|   files.  If "orocos_kdl_vendor" provides a separate development package or
|   SDK, be sure it has been installed.
| 
| 
| -- Configuring incomplete, errors occurred!
```

**Comment by robwoolley** [comment]
Hi @Philip-abl,  Thanks for the words of appreciation!

I notice that it starts by saying that ROS_UNRESOLVED_DEP-liblz4-dev is not provided.  It seems that you are using liblz4-vendor_0.26.1-2.bb which was replaced with a newer version in November 2024.

Regarding the fetcher errors, the ROS release repositories do have a habit of deleting commits.  This is typically solved by me by regenerating the recipes against the latest ROS distro sync every month.

I recommend updating to the latest commit on the scarthgap branch to resolve these issues.

For good measure, I kicked off a fresh build using [https://github.com/ros/meta-ros/blob/build-next/kas/oeros-scarthgap-jazzy-raspberrypi5.yml](https://github.com/ros/meta-ros/blob/build-next/kas/oeros-scarthgap-jazzy-raspberrypi5.yml
)

I had to resolve a minor issue with meta-python-ai (clang-layer vs clang-revival-layer in layer.conf) and saw a build failure in lttng-modules from oe-core.  I was able to successfully build shared-queues-vendor, orocos-kdl-vendor, mcap-vendor, kdl-parser that are mentioned in your output above.   The libyaml-vendor does need to be fixed and is likely related to another libyaml problem that was reported.

Hope that helps
Rob

**Comment by Philip-abl** [comment]
Hi @robwoolley, Thanks for your kind reminding.
Now I'm able to compile Scarthgap + meta-ros2-jazzy. During the build progress, I met some compile issue, I listed here.

1.  Error 1
```shell
ERROR: Nothing RPROVIDES 'ROS_UNRESOLVED_DEP-python3-filelock' (but <layer_path>/meta-ros/meta-ros2-jazzy/generated-recipes/ros2-control/controller-manager_4.32.0-1.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ROS_UNRESOLVED_DEP-python3-filelock' is unbuildable, removing...
``` 
===> My solution is to add 'ROS_UNRESOLVED_DEP-python3-filelock = "python3-filelock"' to local.conf

2.  Error 2
```shell
CMake Error at <out_path>/libyaml-vendor/1.6.3-2/recipe-sysroot/usr/lib/cmake/yaml/yamlConfig.cmake:16 (message):
|   File or directory
|   <out_path>/libyaml-vendor/1.6.3-2/recipe-sysroot/lib/cmake/yaml/yamlTargets.cmake
|   referenced by variable yaml_TARGETS does not exist !
| Call Stack (most recent call first):
|   <out_path>/libyaml-vendor/1.6.3-2/recipe-sysroot/usr/lib/cmake/yaml/yamlConfig.cmake:22 (set_and_check)
|   cmake/Modules/Findyaml.cmake:16 (find_package)
|   CMakeLists.txt:14 (find_package)
| 
| 
| -- Configuring incomplete, errors occurred!
``` 
===> My solution:
```shell
diff --git a/meta-ros-common/recipes-support/libyaml/libyaml_0.2.5.bb b/meta-ros-common/recipes-support/libyaml/libyaml_0.2.5.bb
index df8f84d86..af30ae551 100644
--- a/meta-ros-common/recipes-support/libyaml/libyaml_0.2.5.bb
+++ b/meta-ros-common/recipes-support/libyaml/libyaml_0.2.5.bb
@@ -17,7 +17,7 @@ S = "${WORKDIR}/yaml-${PV}"
 
 inherit cmake
 
-EXTRA_OECMAKE += "-DINSTALL_CMAKE_DIR=${libdir}/cmake/yaml \
+EXTRA_OECMAKE += "-DINSTALL_CMAKE_DIR=${baselib}/cmake/yaml \
                   -DBUILD_TESTING=OFF \
                   -DINSTALL_LIB_DIR=${baselib} \
                   -DBUILD_SHARED_LIBS=ON"
``` 

3.  Error 3
```shell
ERROR: tl-expected-1.0.2-5-r0 do_create_spdx: Cannot find any text for license Creative-Commons-Zero-v1.0-Universal
ERROR: Logfile of failure stored in:<out_path>/tl-expected/1.0.2-5/temp/log.do_create_spdx.1246835
ERROR: Task (<layer_path>/meta-ros/meta-ros2-jazzy/generated-recipes/cpp-polyfills/tl-expected_1.0.2-5.bb:do_create_spdx) failed with exit code '1'
``` 
===> My solution:
```shell
diff --git a/meta-ros2-jazzy/generated-recipes/cpp-polyfills/tl-expected_1.0.2-5.bb b/meta-ros2-jazzy/generated-recipes/cpp-polyfills/tl-expected_1.0.2-5.bb
index fb961da00..00a9891a1 100644
--- a/meta-ros2-jazzy/generated-recipes/cpp-polyfills/tl-expected_1.0.2-5.bb
+++ b/meta-ros2-jazzy/generated-recipes/cpp-polyfills/tl-expected_1.0.2-5.bb
@@ -12,7 +12,7 @@ HOMEPAGE = "https://github.com/TartanLlama/expected"
 SECTION = "devel"
 # Original license in package.xml, joined with "&" when multiple license tags were used:
 #         "Creative Commons Zero v1.0 Universal"
-LICENSE = "Creative-Commons-Zero-v1.0-Universal"
+LICENSE = "CC0-1.0"
 LIC_FILES_CHKSUM = "file://package.xml;beginline=10;endline=10;md5=99bbbc21ede373b77d86a4695cf93337"
 
 ROS_CN = "cpp_polyfills"
``` 

4. Error 4
```shell
tvm-0.7.0-r0 do_fetch: Fetcher failure: Unable to find revision 6c401e242c59a1f4c913918246591bb13fd714e7 in branch master even from upstream
ERROR: tvm-0.7.0-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/dmlc/dmlc-core;name=dlmc-core;destsuffix=git/3rdparty/dmlc-core;branch=master;protocol=https')
``` 
===> My solution: branch name change from "master" to "main"

```shell
diff --git a/meta-ros-common/recipes-devtools/tvm/tvm_0.7.0.bb b/meta-ros-common/recipes-devtools/tvm/tvm_0.7.0.bb
index a15c4c060..a33914bce 100644
--- a/meta-ros-common/recipes-devtools/tvm/tvm_0.7.0.bb
+++ b/meta-ros-common/recipes-devtools/tvm/tvm_0.7.0.bb
@@ -15,7 +15,7 @@ SRCREV_vta-hw = "87ce9acfae550d1a487746e9d06c2e250076e54c"
 SRCREV_FORMAT = "tvm_dlmc-core_dlpack_rang_vta-hw"
 
 SRC_URI = "git://github.com/apache/tvm;name=tvm;branch=main;protocol=https \
-    git://github.com/dmlc/dmlc-core;name=dlmc-core;destsuffix=git/3rdparty/dmlc-core;branch=master;protocol=https \
+    git://github.com/dmlc/dmlc-core;name=dlmc-core;destsuffix=git/3rdparty/dmlc-core;branch=main;protocol=https \
     git://github.com/dmlc/dlpack;name=dlpack;destsuffix=git/3rdparty/dlpack;branch=master;protocol=https \
     git://github.com/agauniyal/rang;name=rang;destsuffix=git/3rdparty/rang;branch=master;protocol=https \
     git://github.com/apache/incubator-tvm-vta;name=vta-hw;destsuffix=git/3rdparty/vta-hw;branch=master;protocol=https \
``` 

5. Error 5
```shell
| -- Found Python3: <out_path>/rsl/1.2.0-1/recipe-sysroot-native/usr/bin/python3-native/python3 (found version "3.12.9") found components: Interpreter
| Traceback (most recent call last):
|   File "<out_path>/rsl/1.2.0-1/recipe-sysroot/opt/ros/jazzy/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py", line 21, in <module>
|     from ament_package.templates import get_environment_hook_template_path
| ModuleNotFoundError: No module named 'ament_package'
``` 
===> My solution:

```shell
diff --git a/meta-ros2-jazzy/generated-recipes/rsl/rsl_1.2.0-1.bb b/meta-ros2-jazzy/generated-recipes/rsl/rsl_1.2.0-1.bb
index 0a0339db1..d1a1b13c5 100644
--- a/meta-ros2-jazzy/generated-recipes/rsl/rsl_1.2.0-1.bb
+++ b/meta-ros2-jazzy/generated-recipes/rsl/rsl_1.2.0-1.bb
@@ -26,6 +26,7 @@ ROS_BUILD_DEPENDS = " \
 
 ROS_BUILDTOOL_DEPENDS = " \
     doxygen-native \
+    ament-cmake-native \
 "
 
 ROS_EXPORT_DEPENDS = " \
``` 

6. Error 6
```shell
ERROR: joint-limits-4.32.0-1-r0 do_compile: ExecutionError('<out_path>/joint-limits/4.32.0-1/temp/run.do_compile.2258248', 1, None, None)
ERROR: Logfile of failure stored in: <out_path>/joint-limits/4.32.0-1/temp/log.do_compile.2258248
......
error: missing braces around initializer for 'std::__array_traits<rclcpp::QosPolicyKind, 9>::_Type' {aka 'rclcpp::QosPolicyKind [9]'} [-Werror=missing-braces]
error: declaration of 'subscription_topic_stats' shadows a previous local [-Werror=shadow]
error: declaration of 'invalid_index' shadows a member of 'rclcpp::exceptions::InvalidServiceNameError' [-Werror=shadow]
error: declaration of 'invalid_index' shadows a member of 'rclcpp::exceptions::InvalidNamespaceError' [-Werror=shadow]
error: declaration of 'invalid_index' shadows a member of 'rclcpp::exceptions::InvalidTopicNameError' [-Werror=shadow]
``` 
===> My solution: make a patch named 0001-rm-cmake-options.patch for ros2-control-cmake_0.2.1.bb
```shell
diff --git a/meta-ros2-jazzy/recipes-bbappends/ros2-control-cmake/ros2-control-cmake/0001-rm-cmake-options.patch b/meta-ros2-jazzy/recipes-bbappends/ros2-control-cmake/ros2-control-cmake/0001-rm-cmake-options.patch
new file mode 100644
index 000000000..51e432f44
--- /dev/null
+++ b/meta-ros2-jazzy/recipes-bbappends/ros2-control-cmake/ros2-control-cmake/0001-rm-cmake-options.patch
@@ -0,0 +1,14 @@
+diff --git a/cmake/ros2_control.cmake b/cmake/ros2_control.cmake
+index 9d74527..06a92f2 100644
+--- a/cmake/ros2_control.cmake
++++ b/cmake/ros2_control.cmake
+@@ -35,8 +35,7 @@ endmacro()
+ macro(set_compiler_options)
+   if(CMAKE_CXX_COMPILER_ID MATCHES "(GNU|Clang)")
+     add_compile_options(-Wall -Wextra -Wpedantic -Werror=conversion -Werror=unused-but-set-variable
+-                        -Werror=return-type -Werror=shadow -Werror=format
+-                        -Werror=missing-braces)
++                        -Werror=return-type -Werror=format)
+     message(STATUS "Compiler warnings enabled for ${CMAKE_CXX_COMPILER_ID}")
+ 
+     # https://docs.ros.org/en/rolling/How-To-Guides/Ament-CMake-Documentation.html#compiler-and-linker-options
diff --git a/meta-ros2-jazzy/recipes-bbappends/ros2-control-cmake/ros2-control-cmake_0.2.1-1.bbappend b/meta-ros2-jazzy/recipes-bbappends/ros2-control-cmake/ros2-control-cmake_0.2.1-1.bbappend
new file mode 100644
index 000000000..e00d9c53a
--- /dev/null
+++ b/meta-ros2-jazzy/recipes-bbappends/ros2-control-cmake/ros2-control-cmake_0.2.1-1.bbappend
@@ -0,0 +1,2 @@
+FILESEXTRAPATHS:prepend := "${THISDIR}/${BPN}:"
+SRC_URI += "file://0001-rm-cmake-options.patch"
``` 

7. Error 7
```shell
ERROR: topic-tools-1.3.3-1-r0 do_patch: Applying patch '0001-setuptools-fix-executable.patch' on target directory '<out_path>/topic-tools/1.3.3-1/git'
CmdError('quilt --quiltrc <out_path>/topic-tools/1.3.3-1/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-setuptools-fix-executable.patch
patching file topic_tools/setup.cfg
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- rejects in file topic_tools/setup.cfg
Patch 0001-setuptools-fix-executable.patch does not apply (enforce with -f)
``` 
===> My solution: update patch "meta-ros/meta-ros2-jazzy/recipes-bbappends/topic-tools/topic-tools/0001-setuptools-fix-executable.patch"
```shell
diff --git a/meta-ros2-jazzy/recipes-bbappends/topic-tools/topic-tools/0001-setuptools-fix-executable.patch b/meta-ros2-jazzy/recipes-bbappends/topic-tools/topic-tools/0001-setuptools-fix-executable.patch
index 876bc9573..0454732f7 100644
--- a/meta-ros2-jazzy/recipes-bbappends/topic-tools/topic-tools/0001-setuptools-fix-executable.patch
+++ b/meta-ros2-jazzy/recipes-bbappends/topic-tools/topic-tools/0001-setuptools-fix-executable.patch
@@ -1,12 +1,12 @@
 diff --git a/topic_tools/setup.cfg b/topic_tools/setup.cfg
-index 7c0fef2..90b577f 100644
+index 0e120fe..ba1fe06 100644
 --- a/topic_tools/setup.cfg
 +++ b/topic_tools/setup.cfg
 @@ -1,5 +1,7 @@
  [develop]
- script-dir=$base/lib/topic_tools
+ script_dir=$base/lib/topic_tools
 +[build]
 +executable=/usr/bin/env python
  [install]
- install-scripts=$base/lib/topic_tools
+ install_scripts=$base/lib/topic_tools
  [options.entry_points]
``` 
8. Error 8
```shell
 | CMake Error at <out_path>/controller-manager/4.32.0-1/recipe-sysroot/opt/ros/jazzy/share/generate_parameter_library/cmake/generate_parameter_library.cmake:34 (message):
|   generate_parameter_library_cpp() variable
|   'generate_parameter_library_cpp_BIN' must not be empty
| Call Stack (most recent call first):
|   CMakeLists.txt:31 (generate_parameter_library)
``` 
===> My solution: 
```shell
diff --git a/meta-ros2-jazzy/recipes-bbappends/ros2-control/controller-manager_4.32.0-1.bbappend b/meta-ros2-jazzy/recipes-bbappends/ros2-control/controller-manager_4.32.0-1.bbappend
index 25b5e4b69..a67c36129 100644
--- a/meta-ros2-jazzy/recipes-bbappends/ros2-control/controller-manager_4.32.0-1.bbappend
+++ b/meta-ros2-jazzy/recipes-bbappends/ros2-control/controller-manager_4.32.0-1.bbappend
@@ -2,6 +2,7 @@
 # Copyright (c) 2022 Wind River Systems, Inc.
 
 ROS_BUILDTOOL_DEPENDS += " \
+    generate-parameter-library-py-native \
     ament-cmake-ros-native \
     python3-numpy-native \
     rosidl-adapter-native \
``` 

9. Error 9, I use Python 3.12 which causes this error.
```shell
|   File "<out_path>/python3-transforms3d/0.3.1/transforms3d-0.3.1/versioneer.py", line 338, in get_config_from_root
|     parser = configparser.SafeConfigParser()
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
| AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
| ERROR: 'python3 setup.py bdist_wheel ' execution failed.
| WARNING: <out_path>/python3-transforms3d/0.3.1/temp/run.do_compile.3678351:180 exit 1 from 'exit 1'
``` 
===> My solution: 
```shell
diff --git a/meta-ros-common/recipes-devtools/python/python3-transforms3d/0001-fix-python3-transforms3d-ConfigParser-error.patch b/meta-ros-common/recipes-devtools/python/python3-transforms3d/0001-fix-python3-transforms3d-ConfigParser-error.patch
new file mode 100644
index 000000000..ca630874d
--- /dev/null
+++ b/meta-ros-common/recipes-devtools/python/python3-transforms3d/0001-fix-python3-transforms3d-ConfigParser-error.patch
@@ -0,0 +1,16 @@
+diff --git a/versioneer.py b/versioneer.py
+index 03b9a96..c98beeb 100644
+--- a/versioneer.py
++++ b/versioneer.py
+@@ -335,9 +335,9 @@ def get_config_from_root(root):
+     # configparser.NoOptionError (if it lacks "VCS="). See the docstring at
+     # the top of versioneer.py for instructions on writing your setup.cfg .
+     setup_cfg = os.path.join(root, "setup.cfg")
+-    parser = configparser.SafeConfigParser()
++    parser = configparser.ConfigParser()
+     with open(setup_cfg, "r") as f:
+-        parser.readfp(f)
++        parser.read_file(f)
+     VCS = parser.get("versioneer", "VCS")  # mandatory
+ 
+     def get(parser, name):
diff --git a/meta-ros-common/recipes-devtools/python/python3-transforms3d_0.3.1.bb b/meta-ros-common/recipes-devtools/python/python3-transforms3d_0.3.1.bb
index abeb58932..fefbe2775 100644
--- a/meta-ros-common/recipes-devtools/python/python3-transforms3d_0.3.1.bb
+++ b/meta-ros-common/recipes-devtools/python/python3-transforms3d_0.3.1.bb
@@ -7,6 +7,8 @@ LIC_FILES_CHKSUM = "file://setup.py;beginline=36;endline=36;md5=6dd3a8a8bcf9d24e
 
 SRC_URI[sha256sum] = "404c7797c78aa461cb8043081901fc5517cef342d5ff56becd74a7967ba88d78"
 
+SRC_URI += "file://0001-fix-python3-transforms3d-ConfigParser-error.patch"
+
 inherit pypi setuptools3
 
 RDEPENDS:${PN} += "\
``` 

10. Error 10
```shell
| sed: can't read <out_path>/ament-download/0.0.5-6/image/usr/share/ament_download/cmake/download_checkmd5.py: No such file or directory
| WARNING: <out_path>/ament-download/0.0.5-6/temp/run.do_install.193747:165 exit 2 from 'sed -i 's@^#!/bin/env@#!/usr/bin/env@g' <out_path>/ament-download/0.0.5-6/image/usr/share/ament_download/cmake/download_checkmd5.py'
``` 
===> My solution: 
```shell
diff --git a/meta-ros2-jazzy/recipes-bbappends/ament-download/ament-download_0.0.5-6.bbappend b/meta-ros2-jazzy/recipes-bbappends/ament-download/ament-download_0.0.5-6.bbappend
index e8adb71ef..3bc397a25 100644
--- a/meta-ros2-jazzy/recipes-bbappends/ament-download/ament-download_0.0.5-6.bbappend
+++ b/meta-ros2-jazzy/recipes-bbappends/ament-download/ament-download_0.0.5-6.bbappend
@@ -5,5 +5,5 @@
 # RDEPENDS:${PN}-dev += "coreutils"
 
 do_install:append() {
-    sed -i 's@^#!/bin/env@#!/usr/bin/env@g' ${D}${datadir}/ament_download/cmake/download_checkmd5.py
+    sed -i 's@^#!/bin/env@#!/usr/bin/env@g' ${D}${ros_prefix}/share/ament_download/cmake/download_checkmd5.py
 }
```
11. Error 11
```shell
Error: 
 Problem: conflicting requests
  - nothing provides python3-flake8-builtins needed by ament-flake8-0.17.2+1-r0.cortexa76 from oe-repo
  - nothing provides python3-flake8-comprehensions needed by ament-flake8-0.17.2+1-r0.cortexa76 from oe-repo
  - nothing provides python3-flake8-docstrings needed by ament-flake8-0.17.2+1-r0.cortexa76 from oe-repo
  - nothing provides python3-flake8-quotes needed by ament-flake8-0.17.2+1-r0.cortexa76 from oe-repo
(try to add '--skip-broken' to skip uninstallable packages)
``` 
===> My solution: 
```shell
diff --git a/meta-ros2-jazzy/generated-recipes/ament-lint/ament-flake8_0.17.2-1.bb b/meta-ros2-jazzy/generated-recipes/ament-lint/ament-flake8_0.17.2-1.bb
index 1d25db122..37a29fc4b 100644
--- a/meta-ros2-jazzy/generated-recipes/ament-lint/ament-flake8_0.17.2-1.bb
+++ b/meta-ros2-jazzy/generated-recipes/ament-lint/ament-flake8_0.17.2-1.bb
@@ -29,11 +29,6 @@ ROS_BUILDTOOL_EXPORT_DEPENDS = ""
 ROS_EXEC_DEPENDS = " \
     ament-lint \
     python3-flake8 \
-    python3-flake8-builtins \
-    python3-flake8-comprehensions \
-    python3-flake8-docstrings \
-    python3-flake8-import-order \
-    python3-flake8-quotes \
 "
 
 # Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
```

**Comment by Nettoysfkf** [comment]
Thanks fix for python3-transforms3d, it works for me.

**Comment by chkohn** [comment]
@Philip-abl  re error 11:
i had the same issue and while most of the python3-flake8 issues are resolved in latest scarthgap + jazzy now, the python3-flake8-docstrings recipe is still broken. Here is a fix: https://github.com/ros/meta-ros/pull/1659
